# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-FormTemplate
version:      2.03
version_from: lib/HTML/FormTemplate.pm
installdirs:  site
requires:
    CGI::MultiValuedHash:          1.09
    Class::ParamParser:            1.041
    Data::MultiValuedHash:         1.081
    HTML::EasyTags:                1.071

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
